Material Serialization
exasmr/openmc pull request #9
Opened 2022-10-31 16:09 UTC by jtramm

This PR serializes materials into global arrays. The global arrays are implemented in the form of a new class, `vector2d<T>`. See the writeup of PR #8 for more info.

2022-11-02 03:20 UTC, paulromano requested changes
This one looks fairly straightforward -- thanks! Just a few small comments.

What performance improvement did you see from just this optimization?

2022-11-02 03:20 UTC, paulromano commented on include/openmc/material.h
> +  gsl::index index_;
Looks to me like this could still be private?

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  size_type footprint() { return size_ * sizeof(T); }
Consider renaming `nbytes` to be more explicit

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  using vector<T>::size_;
This makes these three data members public -- is that really necessary?

2022-11-02 03:20 UTC, paulromano commented on src/device_alloc.cpp
> +    auto& mat = model::materials[i];
```suggestion
    const auto& mat = model::materials[i];
```

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  void copy_row(size_type i, vector<T>& row) {
```suggestion
  void copy_row(size_type i, const vector<T>& row) {
```

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  void copy_row(size_type i, xt::xtensor<T,1>& row) {
```suggestion
  void copy_row(size_type i, const xt::xtensor<T,1>& row) {
```

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  void stretch(vector<T>& vect) {
```suggestion
  void stretch(const vector<T>& vect) {
```

2022-11-02 03:20 UTC, paulromano commented on include/openmc/vector.h
> +  void stretch(xt::xtensor<T,1>& vect) {
```suggestion
  void stretch(const xt::xtensor<T,1>& vect) {
```

2022-11-07 16:35 UTC, jtramm commented on include/openmc/material.h
> +  gsl::index index_;
Good eyes! Yes, in a previous version I was accessing the `index_` field directly, but changed it to use the accessors instead so this should have been restored to private.

2022-11-07 17:43 UTC, jtramm commented
Performance delta on the A100 for this PR is as follows:

  | Old | This PR
-- | -- | --
HM Large Inactive | 356 | 361
SMR Active | 161 | 160

However, it is notable that the differences can be much more dramatic on other GPU architectures (and perhaps even between compilers for A100 down the line) due to how various OpenMP runtimes handle the mapping of millions of pointers.

2022-11-10 13:35 UTC, paulromano approved these changes

2022-11-10 13:35 UTC, merged